/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package org.visualg.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int ALEATORIO = 8;
  /** RegularExpression Id. */
  int ALGORITMO = 9;
  /** RegularExpression Id. */
  int ARQUIVO = 10;
  /** RegularExpression Id. */
  int ASC = 11;
  /** RegularExpression Id. */
  int ATE = 12;
  /** RegularExpression Id. */
  int CARAC = 13;
  /** RegularExpression Id. */
  int CARACPNUM = 14;
  /** RegularExpression Id. */
  int CARACTERE = 15;
  /** RegularExpression Id. */
  int CASO = 16;
  /** RegularExpression Id. */
  int COMPR = 17;
  /** RegularExpression Id. */
  int COPIA = 18;
  /** RegularExpression Id. */
  int CRONOMETRO = 19;
  /** RegularExpression Id. */
  int DEBUG = 20;
  /** RegularExpression Id. */
  int E = 21;
  /** RegularExpression Id. */
  int ECO = 22;
  /** RegularExpression Id. */
  int ENQUANTO = 23;
  /** RegularExpression Id. */
  int ENTAO = 24;
  /** RegularExpression Id. */
  int ESCOLHA = 25;
  /** RegularExpression Id. */
  int ESCREVA = 26;
  /** RegularExpression Id. */
  int ESCREVAL = 27;
  /** RegularExpression Id. */
  int FACA = 28;
  /** RegularExpression Id. */
  int FALSO = 29;
  /** RegularExpression Id. */
  int FIMALGORITMO = 30;
  /** RegularExpression Id. */
  int FIMENQUANTO = 31;
  /** RegularExpression Id. */
  int FIMESCOLHA = 32;
  /** RegularExpression Id. */
  int FIMFUNCAO = 33;
  /** RegularExpression Id. */
  int FIMPARA = 34;
  /** RegularExpression Id. */
  int FIMPROCEDIMENT = 35;
  /** RegularExpression Id. */
  int FIMREPITA = 36;
  /** RegularExpression Id. */
  int FIMSE = 37;
  /** RegularExpression Id. */
  int FUNCAO = 38;
  /** RegularExpression Id. */
  int INICIO = 39;
  /** RegularExpression Id. */
  int INT = 40;
  /** RegularExpression Id. */
  int INTEIRO = 41;
  /** RegularExpression Id. */
  int INTERROMPA = 42;
  /** RegularExpression Id. */
  int LEIA = 43;
  /** RegularExpression Id. */
  int LIMPATELA = 44;
  /** RegularExpression Id. */
  int LOGICO = 45;
  /** RegularExpression Id. */
  int MAIUSC = 46;
  /** RegularExpression Id. */
  int MINUSC = 47;
  /** RegularExpression Id. */
  int MOD = 48;
  /** RegularExpression Id. */
  int NAO = 49;
  /** RegularExpression Id. */
  int NUMPCARAC = 50;
  /** RegularExpression Id. */
  int OU = 51;
  /** RegularExpression Id. */
  int OUTROCASO = 52;
  /** RegularExpression Id. */
  int PARA = 53;
  /** RegularExpression Id. */
  int PASSO = 54;
  /** RegularExpression Id. */
  int PAUSA = 55;
  /** RegularExpression Id. */
  int POS = 56;
  /** RegularExpression Id. */
  int REAL = 57;
  /** RegularExpression Id. */
  int PROCEDIMENTO = 58;
  /** RegularExpression Id. */
  int REPITA = 59;
  /** RegularExpression Id. */
  int RETORNE = 60;
  /** RegularExpression Id. */
  int SE = 61;
  /** RegularExpression Id. */
  int SENAO = 62;
  /** RegularExpression Id. */
  int TIMER = 63;
  /** RegularExpression Id. */
  int VAR = 64;
  /** RegularExpression Id. */
  int VETOR = 65;
  /** RegularExpression Id. */
  int VERDADEIRO = 66;
  /** RegularExpression Id. */
  int XOU = 67;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 68;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 69;
  /** RegularExpression Id. */
  int HEX_LITERAL = 70;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 71;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 72;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 73;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 74;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 75;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 76;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 77;
  /** RegularExpression Id. */
  int STRING_LITERAL = 78;
  /** RegularExpression Id. */
  int IDENTIFIER = 79;
  /** RegularExpression Id. */
  int LETTER = 80;
  /** RegularExpression Id. */
  int PART_LETTER = 81;
  /** RegularExpression Id. */
  int LPAREN = 82;
  /** RegularExpression Id. */
  int RPAREN = 83;
  /** RegularExpression Id. */
  int LBRACE = 84;
  /** RegularExpression Id. */
  int RBRACE = 85;
  /** RegularExpression Id. */
  int LBRACKET = 86;
  /** RegularExpression Id. */
  int RBRACKET = 87;
  /** RegularExpression Id. */
  int SEMICOLON = 88;
  /** RegularExpression Id. */
  int COMMA = 89;
  /** RegularExpression Id. */
  int DOT = 90;
  /** RegularExpression Id. */
  int AT = 91;
  /** RegularExpression Id. */
  int ASSIGN = 92;
  /** RegularExpression Id. */
  int LT = 93;
  /** RegularExpression Id. */
  int BANG = 94;
  /** RegularExpression Id. */
  int TILDE = 95;
  /** RegularExpression Id. */
  int HOOK = 96;
  /** RegularExpression Id. */
  int COLON = 97;
  /** RegularExpression Id. */
  int EQ = 98;
  /** RegularExpression Id. */
  int LE = 99;
  /** RegularExpression Id. */
  int GE = 100;
  /** RegularExpression Id. */
  int NE = 101;
  /** RegularExpression Id. */
  int SC_OR = 102;
  /** RegularExpression Id. */
  int SC_AND = 103;
  /** RegularExpression Id. */
  int INCR = 104;
  /** RegularExpression Id. */
  int DECR = 105;
  /** RegularExpression Id. */
  int PLUS = 106;
  /** RegularExpression Id. */
  int MINUS = 107;
  /** RegularExpression Id. */
  int STAR = 108;
  /** RegularExpression Id. */
  int SLASH = 109;
  /** RegularExpression Id. */
  int BIT_AND = 110;
  /** RegularExpression Id. */
  int BIT_OR = 111;
  /** RegularExpression Id. */
  int XOR = 112;
  /** RegularExpression Id. */
  int REM = 113;
  /** RegularExpression Id. */
  int LSHIFT = 114;
  /** RegularExpression Id. */
  int PLUSASSIGN = 115;
  /** RegularExpression Id. */
  int MINUSASSIGN = 116;
  /** RegularExpression Id. */
  int STARASSIGN = 117;
  /** RegularExpression Id. */
  int SLASHASSIGN = 118;
  /** RegularExpression Id. */
  int ANDASSIGN = 119;
  /** RegularExpression Id. */
  int ORASSIGN = 120;
  /** RegularExpression Id. */
  int XORASSIGN = 121;
  /** RegularExpression Id. */
  int REMASSIGN = 122;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 123;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 124;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 125;
  /** RegularExpression Id. */
  int ELLIPSIS = 126;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"aleatorio\"",
    "\"algoritmo\"",
    "\"arquivo\"",
    "\"asc\"",
    "\"ate\"",
    "\"carac\"",
    "\"caracpnum\"",
    "\"caractere\"",
    "\"caso\"",
    "\"compr\"",
    "\"copia\"",
    "\"cronometro\"",
    "\"debug\"",
    "\"e\"",
    "\"eco\"",
    "\"enquanto\"",
    "\"entao\"",
    "\"escolha\"",
    "\"escreva\"",
    "\"escreval\"",
    "\"faca\"",
    "\"falso\"",
    "\"fimalgoritmo\"",
    "\"fimenquanto\"",
    "\"fimescolha\"",
    "\"fimfuncao\"",
    "\"\\tfimpara\"",
    "\"fimprocedimento\"",
    "\"fimrepita\"",
    "\"fimse\"",
    "\"funcao\"",
    "\"inicio\"",
    "\"int\"",
    "\"inteiro\"",
    "\"interrompa\"",
    "\"\\tleia\"",
    "\"limpatela\"",
    "\"logico\"",
    "\"maiusc\"",
    "\"minusc\"",
    "\"mod\"",
    "\"nao\"",
    "\"numpcarac\"",
    "\"ou\"",
    "\"outrocaso\"",
    "\"\\tpara\"",
    "\"passo\"",
    "\"pausa\"",
    "\"pos\"",
    "\"real\"",
    "\"procedimento\"",
    "\"repita\"",
    "\"retorne\"",
    "\"se\"",
    "\"senao\"",
    "\"timer\"",
    "\"var\"",
    "\"vetor\"",
    "\"verdadeiro\"",
    "\"xou\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
  };

}
